version: "3.4"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.14
    volumes:
      - redis:/var/lib/postgresql/data
    ports:
      - 6379:6379
  faktory:
    image: contribsys/faktory:1.9.1
    ports:
      - 7419:7419
      - 7420:7420
    volumes:
      - faktory:/var/lib/faktory/db
volumes:
  postgres:
  redis:
  faktory:
