version: "3.4"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.14
    volumes:
      - redis:/var/lib/postgresql/data
volumes:
  postgres:
  redis:
